name: Publicando em ambiente de Prod
on:
  push: 
    branches:
      - master

jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configurando credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Instalando dependências do projeto
        run: npm install

      - name: Gerando artefacto do projeto
        run: npm run build

      - name: Publicando na AWS - Ambiente produtivo
        run: aws s3 sync build/ s3://planos.abstartups.com.br --acl public-read